### ISSUE TITLE
preprocessing.py not working

### ISSUE THREAD

**Issue by emacasali** [wzhstat/Reaction-Condition-Selector#1]
Dear Zihan, 
I am testing your software since we wold like to use an in-house made database on specific reactions which are not covered by USPTO database. 
However, before to test our dataset we decided to test your code using the provided USPTO database and we are encountering this error:

Traceback (most recent call last):
  File "/Users/common/Reaction-Condition-Selector/preprocessing.py", line 1, in <module>
    from GetMpnnData import get_MPNN_data, save_csv
  File "/Users/common/Reaction-Condition-Selector/GetMpnnData/__init__.py", line 1, in <module>
    from .get_data import get_MPNN_data, save_csv
  File "/Users/common/Reaction-Condition-Selector/GetMpnnData/get_data.py", line 2, in <module>
    import pandas as pd
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

We followed your procedure for the installation of the conda environment.
Let us knnow how we can proceed or fix the problem.
Thanks in advance, 
Ema

**Comment by wzhstat** [comment]
Hi!
This seems to be an issue triggered by the version of `numpy` . `numpy` from version 2.0.0 onwards is no longer compatible with the version of pandas we are using. A possible solution is to lower the `numpy` version to any before 2.0.0. For reference, the version we are using is 1.24.4.
Let me know if this doesn't work or if there are any more problems.

**Comment by emacasali** [comment]
Thanks, I downgraded to numpy to 1.26.4 and now it works fine!

**Comment by emacasali** [comment]
The script now works, but get stucked at the point of epochs. See the attached error:

Number of parameters = 510,439
  0%|                                                                                                        | 0/35 [00:00<?, ?it/s]
Epoch 0
  0%|                                                                                                        | 0/35 [02:25<?, ?it/s]
Traceback (most recent call last):                                                                                                  
  File "/opt/anaconda3/envs/Cluster_Predictor/bin/chemprop_train", line 8, in <module>
    sys.exit(chemprop_train())
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/train/cross_validate.py", line 208, in chemprop_train
    cross_validate(args=TrainArgs().parse_args(), train_func=run_training)
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/utils.py", line 591, in wrap
    result = func(*args, **kwargs)
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/train/cross_validate.py", line 119, in cross_validate
    model_scores = train_func(args, data, logger)
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/train/run_training.py", line 295, in run_training
    n_iter = train(
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/train/train.py", line 53, in train
    for batch in tqdm(data_loader, total=len(data_loader), leave=False):
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/data/data.py", line 839, in construct_molecule_batch
    data.batch_graph()  # Forces computation and caching of the BatchMolGraph for the molecules
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/data/data.py", line 407, in batch_graph
    mol_graph = MolGraph(m, d.atom_features, d.bond_features,
  File "/opt/anaconda3/envs/Cluster_Predictor/lib/python3.10/site-packages/chemprop/features/featurization.py", line 362, in __init__
    self.f_atoms = [atom_features(atom) for atom in mol.GetAtoms()]
AttributeError: 'tuple' object has no attribute 'GetAtoms'

**Comment by wzhstat** [comment]
I'm sorry , but I wasn't able to reproduce the situation you're asking about, so I can't confirm the exact cause of the error. I'll give a few possible reasons here:
1. From the error message, this seems to be a problem with data loading. I've run into similar situations before, and this mainly occurs when trying to do Chemprop training on a Windows system. Trying to run it on a Linux system might help.
2. I have also noticed that your model is not moving to cuda, I'm not quite sure why. Maybe checking the cuda version again would help.

**Comment by wzhstat** [comment]
For the training part we are using `Chemprop` directly. Detailed information about this package can be found in their README file: https://github.com/chemprop/chemprop/blob/v1.7.1/README.md. Hopefully it can be helpful for you.
